config/routes.rb
CfaRubyTest::Application.routes.draw do
  resources :wall_posts

end

app/models/wall_post.rb
class WallPost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wall_posts_controller.rb
class WallPostsController < ApplicationController
  before_action :set_wall_post, only: [:show, :edit, :update, :destroy]

  # GET /wall_posts
  # GET /wall_posts.json
  def index
    @wall_posts = WallPost.all
  end

  # GET /wall_posts/1
  # GET /wall_posts/1.json
  def show
  end

  # GET /wall_posts/new
  def new
    @wall_post = WallPost.new
  end

  # GET /wall_posts/1/edit
  def edit
  end

  # POST /wall_posts
  # POST /wall_posts.json
  def create
    @wall_post = WallPost.new(wall_post_params)

    respond_to do |format|
      if @wall_post.save
        format.html { redirect_to @wall_post, notice: 'Wall post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wall_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @wall_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wall_posts/1
  # PATCH/PUT /wall_posts/1.json
  def update
    respond_to do |format|
      if @wall_post.update(wall_post_params)
        format.html { redirect_to @wall_post, notice: 'Wall post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wall_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wall_posts/1
  # DELETE /wall_posts/1.json
  def destroy
    @wall_post.destroy
    respond_to do |format|
      format.html { redirect_to wall_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall_post
      @wall_post = WallPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_post_params
      params.require(:wall_post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wall_posts_helper.rb
module WallPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CfaRubyTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wall_posts/_form.html.erb
<%= form_for(@wall_post) do |f| %>
  <% if @wall_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wall_post.errors.count, "error") %> prohibited this wall_post from being saved:</h2>

      <ul>
      <% @wall_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wall_posts/edit.html.erb
<h1>Editing wall_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @wall_post %> |
<%= link_to 'Back', wall_posts_path %>

app/views/wall_posts/index.html.erb
<h1>Listing wall_posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wall_posts.each do |wall_post| %>
      <tr>
        <td><%= wall_post.title %></td>
        <td><%= wall_post.body %></td>
        <td><%= link_to 'Show', wall_post %></td>
        <td><%= link_to 'Edit', edit_wall_post_path(wall_post) %></td>
        <td><%= link_to 'Destroy', wall_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wall post', new_wall_post_path %>

app/views/wall_posts/new.html.erb
<h1>New wall_post</h1>

<%= render 'form' %>

<%= link_to 'Back', wall_posts_path %>

app/views/wall_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wall_post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @wall_post.body %>
</p>

<%= link_to 'Edit', edit_wall_post_path(@wall_post) %> |
<%= link_to 'Back', wall_posts_path %>